---
title: "Mini_Project"
author: "Xindi Lu,Jingyu Xie"
date: "October 2, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(gapminder)
library(dplyr)
library(ggplot2)
library(tidyr)
```


## 1.GDP and life expectancy in 2018
```{r echo = FALSE}
lifeExpectancy <- read.csv("life_expectancy_years.csv")
GDPpercapita <- read.csv("income_per_person_gdppercapita_ppp_inflation_adjusted.csv")
colnames(lifeExpectancy) <- c("country", 1800:2018)
colnames(GDPpercapita) <- c("country", 1800:2040)
```

```{r echo = FALSE}
country_continent <- subset(gapminder, subset = year == 1952, select = c(country, continent))
```

```{r echo = FALSE, message = FALSE}
library(tidyverse)
lifeExpectancy_cc <- merge(country_continent, lifeExpectancy, by = 'country')
GDPpercapita_cc <- merge(country_continent, GDPpercapita, by = 'country')
dataset1 <- data.frame(GDPpercapita_cc_2018 = GDPpercapita_cc$`2018`, lifeExpectancy_cc_2018 = lifeExpectancy_cc$`2018`,
                      country = GDPpercapita_cc$country, continent = GDPpercapita_cc$continent)
#ggplot(dataset1, aes(x = GDPpercapita_cc_2018, y = lifeExpectancy_cc_2018)) + geom_point() + geom_smooth(method = 'gam', formula = y ~ sqrt(x), se = FALSE)

ggplot(dataset1, aes(x = GDPpercapita_cc_2018, y = lifeExpectancy_cc_2018)) + geom_point() + facet_wrap(~ continent)  + geom_smooth(method = 'gam', formula = y ~ sqrt(x), se = FALSE)

```



## 2.Life expectancy over time by continent
```{r}
population <- read.csv("population_total.csv")
colnames(population) <- c("country", 1800:2100)
population_cc <- merge(country_continent, population, by = 'country')
population_cc_gather <- population_cc %>% gather(key = "year", value = "population", -c(country, continent)) %>% 
                                          filter(year <= 2018) 
```

```{r echo = FALSE}
dataset3 <- gather(lifeExpectancy_cc, key = "year", "lifeExpectancy", -c(country, continent))

average_lifeExpectancy_continent_year <- dataset3 %>% filter(year >= 1939) %>% group_by(continent, year) %>% 
                                                           summarise(averageLifeExpectancy = mean(lifeExpectancy))
ggplot(average_lifeExpectancy_continent_year, aes(x = year, y = averageLifeExpectancy, group = continent, color = continent)) + geom_line()+ scale_x_discrete(breaks = seq(1950, 2020, by = 10))
```



##3.Changes in the relationship between GDP and life expectancy over time

```{r}

GDPpercapita_cc_upto2018 <- subset(GDPpercapita_cc, select = country:`2018`)
dataset5 <- gather(GDPpercapita_cc_upto2018, key = "year", value = "GDPpercapita", -c(country, continent))
average_GDPpercapita_continent_year <- dataset5 %>% filter(year >= 1939) %>% group_by(continent, year) %>% 
                                                           summarise(averageGDPpercapita = mean(GDPpercapita))
dataset6 <- cbind(average_lifeExpectancy_continent_year, average_GDPpercapita_continent_year)
ggplot(dataset6, aes(x = averageGDPpercapita, y = averageLifeExpectancy, group = continent, color = continent)) + geom_point()

```

