---
title: "Mini_Project"
author: "Xindi Lu"
date: "October 2, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

life <- read.csv("life_expectancy_years.csv")

income <- read.csv("income_per_person_gdppercapita_ppp_inflation_adjusted.csv")

pop <- read.csv("population_total.csv")

```

```{r}
library(gapminder)
library(dplyr)
library(ggplot2)
library(tidyr)
```


## 1.GDP and life expectancy in 2018
```{r}
life_2018 <- life[, c(1,220)]
income_2018 <- income[, c(1,220)]
total_2018 <- merge(life_2018, income_2018, by = "country")
colnames(total_2018) <- c("country", "lifeExp", "gdpPercap")
country_2018 <- gapminder[, c(1,2)]
newcountry_2018 <- distinct(country_2018, country, .keep_all = TRUE)
new_2018 <- merge(total_2018, newcountry_2018, by = "country")
```


```{r}
ggplot(new_2018, aes(x = gdpPercap, y = lifeExp, col = continent)) + geom_point() + facet_wrap(continent ~ .)

```




## 2.Life expectancy over time by continent
```{r}
ww2_lf <- life[c(1:187),c(1,141:220)]

ww2 <- merge(ww2_lf, newcountry_2018, by = "country")







```



##3.Changes in the relationship between GDP and life expectancy over time
```{r}

```

